# This is a basic workflow to help you get started with Actions

name: Auto Surge Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    #uses is a tag which tells github to use a certain thing. there are certain things which are already done by github to the point where we can just assume somethings such as it will pick all the project code etc.
    # Runs a single command using the runners shell
    - name: Installing node module
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  

    # Runs a set of commands using the runners shell
    - name: Installing surge
      run: npm install -g surge
    - name: Deploying on surge
      #./ means this same project. This is the representation of local URL in the same command on our local system
      run: surge ./ http://practicingsurge.surge.sh --token ${{secrets.SURGE_TOKEN}}
